<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hardware.proto

namespace Spikelib\Grpc\Hardware;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>spikelib.grpc.hardware.HardwareRequest</code>
 */
class HardwareRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cid = 1;</code>
     */
    protected $cid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Hardware::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cid = 1;</code>
     * @return string
     */
    public function getCid()
    {
        return $this->cid;
    }

    /**
     * Generated from protobuf field <code>string cid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCid($var)
    {
        GPBUtil::checkString($var, True);
        $this->cid = $var;

        return $this;
    }

}

